[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Permissions-Policy = "camera=(self), microphone=(self), fullscreen=(self)"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
